### ISSUE TITLE
Not working on Ubuntu 20.04.1 LTS with Go 1.13.8

### ISSUE THREAD

**Issue by eparra** [m-mizutani/falconstream#1]
**My Setup**

```
root@dev:~# uname -a
Linux dev 5.4.0-62-generic #70-Ubuntu SMP Tue Jan 12 12:45:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

root@dev:~# go version
go version go1.13.8 linux/amd64
```

**Issue**

```
root@dev:~# go get github.com/m-mizutani/falconstream
# github.com/m-mizutani/falconstream
go/src/github.com/m-mizutani/falconstream/main.go:29:14: cannot use []cli.Author literal (type []cli.Author) as type []*cli.Author in assignment
go/src/github.com/m-mizutani/falconstream/main.go:37:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/m-mizutani/falconstream/main.go:43:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/m-mizutani/falconstream/main.go:49:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/m-mizutani/falconstream/main.go:54:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/m-mizutani/falconstream/main.go:59:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/m-mizutani/falconstream/main.go:64:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
root@dev:~# 
```

**Comment by eparra** [comment]
**Also Tried**

```
root@dev:~/dev/go# go version
go version go1.15.6 linux/amd64
```

**Same Outcome**

```
root@dev:~/dev/go# go get github.com/m-mizutani/falconstream
# github.com/m-mizutani/falconstream
/root/go/src/github.com/m-mizutani/falconstream/main.go:29:14: cannot use []cli.Author literal (type []cli.Author) as type []*cli.Author in assignment
/root/go/src/github.com/m-mizutani/falconstream/main.go:37:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
/root/go/src/github.com/m-mizutani/falconstream/main.go:43:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
/root/go/src/github.com/m-mizutani/falconstream/main.go:49:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
/root/go/src/github.com/m-mizutani/falconstream/main.go:54:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
/root/go/src/github.com/m-mizutani/falconstream/main.go:59:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
/root/go/src/github.com/m-mizutani/falconstream/main.go:64:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
```
